example code to manage cronjobs
Shapeways/puppetarium pull request #2
Opened 2016-09-26 21:18 UTC by swwolf

2016-09-27 17:25 UTC, ChairmanTubeAmp requested changes

2016-09-27 17:25 UTC, ChairmanTubeAmp commented on modules/profiles/manifests/cron.pp
> +class profiles::cron($data = '') {
Should get all data from params.pp.

2016-09-27 18:11 UTC, obi11235 requested changes

2016-09-27 18:11 UTC, obi11235 commented on modules/profiles/manifests/cron.pp
> +      source => 'puppet:///modules/profiles/cron/cronjobber.c',
line up your =>

2016-09-27 18:19 UTC, d33psky reviewed
,

2016-09-27 18:19 UTC, d33psky commented on modules/profiles/manifests/cron.pp
> +    creates => '/usr/local/bin/cronjobber'
,

2016-09-27 18:25 UTC, obi11235 approved these changes

2016-09-28 14:02 UTC, ChairmanTubeAmp approved these changes

2016-09-28 14:02 UTC, merged